name: masamune_firebase
description: >-
  Module for supporting the Firebase/Firestore function of Masamune framework.
  It is also available on the web.
version: 0.6.2+3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_firebase


environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Web
  http: ^0.12.1
  # Device
  package_info: ^0.4.0+13
  # Firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  firebase_dynamic_links: ^0.6.0+2
  firebase_remote_config: ^0.4.0+2
  geoflutterfire: ^2.2.1
  # Masamune
  masamune: ^0.6.0
  masamune_core: ^0.6.0
  masamune_flutter: ^0.6.0
  masamune_localize: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.5.0
  
# dependency_overrides:
#   masamune_core:
#     path: ../masamune_core/
#   masamune_localize:
#     path: ../masamune_localize/
#   masamune_flutter:
#     path: ../masamune_flutter/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
